---
deployment:
  tasks:
    - export DEPLOYPATH=/home/polioantennaorg/public_html/polio-collector
    - mkdir -p $DEPLOYPATH
    - /bin/cp app.html $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp -R models $DEPLOYPATH
    - /bin/cp -R controllers $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R tmp $DEPLOYPATH
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R .well-known $DEPLOYPATH
    - /bin/cp -R cgi-bin $DEPLOYPATH
    
    #- /bin cp * $DEPLOYPATH
    #- /bin/cp -R * $DEPLOYPATH
    #- /bin/cp -R . $DEPLOYPATH